# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter (Deploy)

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Update dependencies
        run: flutter --version && flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Tests
        run: flutter test --coverage
      - name: Archive Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/lcov.info
      - name: Build Web
        run: flutter build web
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POMODORO_A2996 }}'
          channelId: live
          projectId: pomodoro-a2996
