# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Update dependencies
        run: flutter --version && flutter pub get
      - name: Build Web
        run: flutter build web
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
